{% set version = "1.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-checkpoint
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/checkpoint_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/checkpoint/checkpoint_{{ version }}.tar.gz
  sha256: d36146093763ca29e0296729399b96e0f2e7764745283d6cea1066a96fa085a7

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('checkpoint')"           # [not win]
    - "\"%R%\" -e \"library('checkpoint')\""  # [win]

about:
  home: https://github.com/RevolutionAnalytics/checkpoint
  license: GPL-2.0-only
  summary: The goal of checkpoint is to solve the problem of package reproducibility in R. Specifically, checkpoint allows you to install packages as they existed on CRAN on a specific snapshot date as if you had a CRAN time machine. To achieve reproducibility, the checkpoint() function installs the packages required or
    called by your project and scripts to a local library exactly as they existed at the specified point in time. Only those packages are available to your project, thereby avoiding any package updates that came later and may have altered your results. In this way, anyone using checkpoint's checkpoint() can ensure the reproducibility
    of your scripts or projects at any time. To create the snapshot archives, once a day (at midnight UTC) Microsoft refreshes the Austria CRAN mirror on the "Microsoft R Archived Network" server (<https://mran.microsoft.com/>). Immediately after completion of the rsync mirror process, the process takes a snapshot, thus
    creating the archive. Snapshot archives exist starting from 2014-09-17.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: checkpoint
# Title: Install Packages from Snapshots on the Checkpoint Server for Reproducibility
# Description: The goal of checkpoint is to solve the problem of package reproducibility in R. Specifically, checkpoint allows you to install packages as they existed on CRAN on a specific snapshot date as if you had a CRAN time machine. To achieve reproducibility, the checkpoint() function installs the packages required or called by your project and scripts to a local library exactly as they existed at the specified point in time. Only those packages are available to your project, thereby avoiding any package updates that came later and may have altered your results. In this way, anyone using checkpoint's checkpoint() can ensure the reproducibility of your scripts or projects at any time. To create the snapshot archives, once a day (at midnight UTC) Microsoft refreshes the Austria CRAN mirror on the "Microsoft R Archived Network" server (<https://mran.microsoft.com/>). Immediately after completion of the rsync mirror process, the process takes a snapshot, thus creating the archive. Snapshot archives exist starting from 2014-09-17.
# Version: 0.4.7
# Authors@R: c( person("Hong", "Ooi", , "hongooi@microsoft.com", role=c("aut", "cre")), person("Microsoft", role="cph") )
# License: GPL-2
# URL: https://github.com/RevolutionAnalytics/checkpoint
# BugReports: https://www.github.com/RevolutionAnalytics/checkpoint/issues
# Imports: utils
# Depends: R(>= 3.0.0)
# Suggests: knitr, rmarkdown, testthat(>= 0.9), MASS, darts, mockery, cli
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-09-08 21:10:09 UTC; hongo
# Author: Hong Ooi [aut, cre], Microsoft [cph]
# Maintainer: Hong Ooi <hongooi@microsoft.com>
# Repository: CRAN
# Date/Publication: 2019-09-08 21:30:02 UTC
