travis:
  secure:
    BINSTAR_TOKEN: Si412AgnY6jC88V2U2iG/LQqLZCCtPKJbQSljn7PvGw9y1iYPBnIZBSvu+BbsWPx8ekjye35kHi2ygDKGxP2LNtvQKtjPFI8jj5RL3asTIV/bKq4h0Lwe89uK36oRc6NOilV0kgqlonC2biEDXLumZJ6bEG45ctw/SfjuBnLx01SGN6ma2wPU6tDannFCC2DJ8o3j7/tcnMPzEBVntE/n3OvhjwWEoxtFPzczHGLrUUWeLnriiPnuXciv9byawoV0aShbs6YIo3a+kdhSPQa/8vrORS55xahQbQxARaRlShyfkLJNLy8UX7KO72aGAJ93RbWALTPiq9FGKjB9D6MEE0K1qsGu/wYTqsTlx/flgpEzoiqX8yjFlLjhXkgh9gTH8+E32CT78BEOiYMp7xbY+JgQgh9gsfL5zqx8aRahXg4Wii/yOYbd77x+Kp5ky+lV5bs8KgDrW9DTUnKsU36bIZMxPvg6Sq9NZZpqkR3+BAFU5FxdzbshFSTJ5q9EIgkEQJDksviEjkKJ/HjiliDFUvAZ2hg9JYXdEkT2qdCEM12i0BsUd/DramWGDyyM89SWEmuEfrAtgnIc2YQysPYpW5T933vrTcr1LQU+dIAipKVhVGoGfBq/s0dtvd4ZPWmAQ+lMdQPaBsH8omNMucCRTX+XZyJJSP/q28wAsshaok=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
